version: '2'

services:
    workspace:
      env_file: .env
      # depends_onで依存関係を示す.appでmysqlを使いたいのでdbコンテナを指定.
      # build はDockerfileからビルドすることを示す.
      # pathは相対パスになるので、build/app/Dockerfileが読まれる.
      build: "./php53-apache"
      # ports でポートフォワーディングを指定.
      ports:
        - $PORT:$PORT
      # volumes でマウントの指定.こちらも相対パス.
      volumes:
        - ./workspace:/var/www/html
        - ./httpd.conf:/etc/httpd/conf/httpd.conf
      # links で連携させるコンテナを示す.
      # depends_onはビルド時に依存関係を考慮してビルドさせるために指定.
      # links は appコンテナの/etc/hostsにdbのipを記述してくれる.
      links:
        - postgres

    postgres:
      restart: always
      image: postgres
      environment:
        LC_ALL: C.UTF-8
        POSTGRES_USER: $POSTGRES_USER
        POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      volumes:
        - ./pgsql-data:/var/lib/pgsql/data
      ports:
        - $DB_PORT:$DB_PORT
