<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2019/04/07 06:46:01

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'pgsql:host=postgres;dbname=symfodock',
  'username' => 'sf14',
  'password' => 'password',
  'name' => 'doctrine',
)),);
