<?php

/**
 * BaseStaff
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property string $kana
 * @property clob $comment
 * 
 * @method string get()        Returns the current record's "name" value
 * @method string get()        Returns the current record's "kana" value
 * @method clob   get()        Returns the current record's "comment" value
 * @method Staff  set()        Sets the current record's "name" value
 * @method Staff  set()        Sets the current record's "kana" value
 * @method Staff  set()        Sets the current record's "comment" value
 * 
 * @package    ./
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseStaff extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('staff');
        $this->hasColumn('name', 'string', 100, array(
             'type' => 'string',
             'notnull' => true,
             'default' => '',
             'length' => 100,
             ));
        $this->hasColumn('kana', 'string', 100, array(
             'type' => 'string',
             'notnull' => true,
             'default' => '',
             'length' => 100,
             ));
        $this->hasColumn('comment', 'clob', null, array(
             'type' => 'clob',
             'notnull' => true,
             'default' => '',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}