<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2018/07/01 15:12:50

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=sf14',
  'username' => 'root',
  'password' => NULL,
  'name' => 'doctrine',
)),);
