# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/10-Routing

homepage:
  url:      /
  param:    { module: Page, action: Show, slug: top }

page_show:
  url:      /page/:slug
  param:    { module: Page, action: Show }

news_list:
  url:      /news
  param:    { module: Page, action: NewsList }

news_show:
  url:      /news/:slug
  param:    { module: Page, action: NewsShow }

inquiry_new:
  url:      /inquiry/new
  param:    {module: Inquiry, action: New }

inquiry_complete:
  url:      /inquiry/complete
  param:    {module: Inquiry, action: Complete }
