# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/10-Routing

# default rules
homepage:
  url: /
  param: { module: Page, action: Show, slug: top }

page_show:
  url: /page/:slug
  param: { module: Page, action: Show }

# generic rules
# please, remove them by adding more specific rules
news_list:
  url: /news
  param: { module: Page, action: NewsList }

news_show:
  url: /news/:slug
  param: { module: Page, action: NewsShow }

inquiry_complete:
  url: /inquiry/complete
  param: { module: Inquiry, action: Complete }

default:
  url: /:module/:action

inquiry_new:
  url: /inquiry/new
  param: { module: Inquiry, action: New }
